spring.application.name=mini-e-commerce

spring.datasource.url=jdbc:postgresql://localhost:5432/mini-e-commerce
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Tells Hibernate how to translate its SQL into PostgreSQL-specific SQL.
#Without this, Hibernate may not use PostgreSQL-optimized syntax.

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.open-in-view=false
spring.cache.type=none

logging.level.org.springframework.security=DEBUG

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
jwt.refreshExpirationMs=86400000
